apiVersion: platform.stackrox.io/v1alpha1
kind: SecuredCluster
metadata:
  name: stackrox-secured-cluster-services
  namespace: stackrox
spec:
  clusterName: managed-cluster01
  # Update with your central cluster endpoint (route hostname + :443)
  # Example: central-stackrox.apps.<cluster-domain>:443
  centralEndpoint: central-stackrox.apps.<cluster-domain>:443
